Parameters:
  AmiId:
    Type: String
    Default: ami-a123b456
  InstanceType:
    Type: String
    Default: t2.medium

Resources:
  WebVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: skipjaq-web
  WebPublicA:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: eu-west-1a
        VpcId: !Ref WebVpc
  WebPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-1b
      VpcId: !Ref WebVpc
  WebPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: eu-west-1c
      VpcId: !Ref WebVpc
  WebPrivateA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.100.0/24
      AvailabilityZone: eu-west-1a
      VpcId: !Ref WebVpc
  WebPrivateB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.101.0/24
      AvailabilityZone: eu-west-1b
      VpcId: !Ref WebVpc
  WebPrivateC:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.102.0/24
      AvailabilityZone: eu-west-1c
      VpcId: !Ref WebVpc

  WebInternetGateway:
    Type: AWS::EC2::InternetGateway
  WebInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref WebInternetGateway
      VpcId: !Ref WebVpc
  WebPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebVpc
  WebPublicRouteToInternet:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WebInternetGateway
      RouteTableId: !Ref WebPublicRouteTable
  WebPublicRouteTableSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref WebPublicRouteTable
      SubnetId: !Ref WebPublicA
  WebPublicRouteTableSubnetB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref WebPublicRouteTable
      SubnetId: !Ref WebPublicB
  WebPublicRouteTableSubnetC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref WebPublicRouteTable
      SubnetId: !Ref WebPublicC

  WebLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web load balancer
      VpcId: !Ref WebVpc
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  WebTargetsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web targets
      VpcId: !Ref WebVpc
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        SourceSecurityGroupId: !Ref WebLBSecurityGroup

  WebLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
      - !Ref WebPublicA
      - !Ref WebPublicB
      - !Ref WebPublicC
      SecurityGroups:
      - !Ref WebLBSecurityGroup
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: skipjaq-web
      Port: 8080
      Protocol: HTTP
      HealthCheckIntervalSeconds: 15
      UnhealthyThresholdCount: 8
      HealthCheckPort: 8080
      HealthCheckPath: /health
      VpcId: !Ref WebVpc
  WebServiceListener:
    Type : AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref WebLoadBalancer
      Port: 80
      Protocol: HTTP

  WebLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebTargetsSecurityGroup
  WebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref WebPrivateA
        - !Ref WebPrivateB
        - !Ref WebPrivateC
      LaunchConfigurationName: !Ref WebLaunchConfiguration
      MinSize: 6
      MaxSize: 15
      TargetGroupARNs:
        - !Ref WebTargetGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 3
        MaxBatchSize: 3
  WebScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref WebAutoScalingGroup
      Cooldown: '120'
      ScalingAdjustment: '1'
  WebHighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '60'
      AlarmDescription: CPU too high or metric does not exist (instance down)
      Period: '60'
      AlarmActions:
      - !Ref WebScaleUpPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref WebAutoScalingGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization